#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "enum.h"
#include <memory>
#include <cstring>
#include <time.h>
#include <stdio.h>
#include <iostream>

#define NOT_ERROR_CONTINUE 10000
#define END_OF_WORKING_QUIT -10
#define END_OF_WORKING_STOP -20
#define EMPTY_REQUEST -2

#define ERROR_CANNOT_OPEN_INPUT_FILE -1
#define ERROR_CANNOT_OPEN_OUTPUT_FILE -2
#define ERROR_CANNOT_READ_INPUT_FILE -3
#define ERROR_CANNOT_WRITE_TO_OUTPUT_FILE -4
#define ERROR_WORKING_WITH_EMPTY_OBJECT -5
#define ERROR_CANNOT_ALLOCATE_MEMMORY_TO_READ_NAME -6
#define ERROR_INCORRECT_ENTERED_TYPE -7

#define ERROR_SERVER_CANNOT_PRINT -100
#define ERROR_SERVER_CANNOT_READ -200
#define ERROR_SERVER_CLIPPED -300
#define ERROR_SERVER_CANNOT_READ_INCORRECT_SIZE -400
#define ERROR_SERVER_CANNOT_CREATE_SOCKET -500
#define ERROR_SERVER_CANNOT_BIND_SOCKET -600
#define ERROR_SERVER_CANNOT_LISTEN_QUEUE -700
#define ERROR_SERVER_CANNOT_SELECT_SOCKET -800
#define ERROR_SERVER_WASNOT_ACCEPTED -900
#define NOT_ERROR_SERVER_EMPTY_REQUEST -1000

#define BUFF_LEN 1024
#define LEN_STR 4096
#define SPACE_LEN 256
#define ESCAPE_LEN 3
#define MAX_PRINT_LIST 50
#define MAX_PRINT_TREE 7
#define MAX_PRINT_HASH 20

#endif // CONSTANTS_H
