#define LOGOWIDTH 1000
#define LEN 1234
#define MAX_PRINT 30
#define NOT_ERROR_END_OF_INPUT 1000000
#define ERROR_CANNOT_OPEN_INPUT_FILE -1
#define ERROR_CANNOT_INITIALIZE_STUDENT_NAME -2
#define ERROR_CANNOT_READ_INPUT_FILE -3
#define ERROR_CANNOT_ALLOCATE_MEMMORY -4

#define BUBBLE_SORT 1
#define MAX_FIN_SORT 2
#define MIN_FIN_SORT 3
#define LIN_IN_SORT 4
#define NEWMAN_SORT 5
#define QUICK_SORT 6
