
#define LEN 1234
#define MAX_PRINT_LIST 20
#define NOT_ERROR_END_OF_INPUT 1000000
#define ERROR_CANNOT_OPEN_INPUT_FILE -1
#define ERROR_CANNOT_INITIALIZE_STRING_NAME -2
#define ERROR_CANNOT_READ_INPUT_FILE -3
#define ERROR_CANNOT_ALLOCATE_MEMMORY -4
#define ERROR_EMPTY_INPUT_FILE -5
