#ifndef ADDITION_H
#define ADDITION_H

#define MAX_PRINT 4
#define ERROR_CANNOT_OPEN_INPUT_FILE -1
#define ERROR_CANNOT_READ_INPUT_FILE -2
#define ERROR_CANNOT_READ_CLASS -3
#define ERROR_CANNOT_INITIALIZE_STUDENT_NAME -4
#define ERROR_NOT_ENOUGH_MEMORY -5
#define ERROR_END_OF_INPUT_FILE 1

#endif
