#ifndef CONST_H
#define CONST_H

#define LOGOWIDTH 1000
#define MAX_PRINT 3
#define MAX_LEN_PRINT 5
#define MAX_HEIGHT_PRINT 3
#define NOT_ERROR_END_OF_INPUT 1
#define ERROR_CANNOT_OPEN_INPUT_FILE -1
#define ERROR_CANNOT_INITIALIZE_STUDENT_NAME -2
#define ERROR_CANNOT_READ_INPUT_FILE -3
#define ERROR_CANNOT_ALLOCATE_MEMMORY -4

#endif